### PR TITLE
Kayran set

### LINKED ISSUE #2: Kayran Set
* [x] Kayran Cleaver
* [x] Kayran Shears
* [x] Kayran Scythe
* [x] Kayran Shovel
* [ ] Kayran Crossbow
* [x] Kayran Blade
Screen Shot 2020-11-17 at 2 53 04 pm
Screen Shot 2020-11-17 at 2 53 18 pm
Screen Shot 2020-11-17 at 2 53 30 pm
Screen Shot 2020-11-17 at 2 53 56 pm
Screen Shot 2020-11-17 at 2 54 09 pm
Screen Shot 2020-11-17 at 2 54 24 pm

### PR DESCRIPTION
**Pull request by resindrake**

### CODE REVIEW

**Comment by resindrake** [comment]
Rough drafts
image
image

**Review by FeignedIgnorance — CHANGES_REQUESTED** [review]
A good palette for the tool set! Some things to add may be the colour orange in either animal skin, edges of the blades, or perhaps orange rope with some kind with a white tooth attached? The vines are a good feature and are pretty spot on in how they are coloured. try to make the darker colours significantly darker especially the underside of the handles. They are hard to distinguish while small in scale.

Summary:
* add may be the colour orange in either animal skin, edges of the blades
  * perhaps orange rope with some kind with a white tooth attached
* try to make the darker colours significantly darker especially the underside of the handles

**Comment by resindrake** [comment]
My main concern is that adding the rope and the tooth makes the texture become too detailed.

image
image

**Comment by FeignedIgnorance** [comment]
Hmm... Perhaps try the orange on the blade edge? like with the titanium set but instead of white it would be orange.

**Comment by resindrake** [comment]
image
?

**Comment by FeignedIgnorance** [comment]
I like that a lot! Definitely gives the Kayran palette a unique identity. I think that's a good final product for the cleaver. Would you mind If I did minor adjustments to your Kayran Blade? A blade template already exists in the form of the Demagorgon's blade. So following that format would help with texture pack consistency.

**Pull request merged**
